### ISSUE TITLE
Can't start the project

### ISSUE THREAD

**Issue by anteljubic** [GoranTolusic/news#1]
Hi Goran,

I followed steps from the readme file and I stuck on the 2. step, I can't run the app, the installation breaks, here is the log from terminal:

```bash
$ npm run installAndRun

> expresstype@1.0.0 installAndRun
> rm -rf node_modules/ && rm -rf package-lock.json && npm i && npm run seedAdmins && npm run seedNews && npm run start

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: typeorm@0.3.11
npm ERR! Found: mongodb@4.13.0
npm ERR! node_modules/mongodb
npm ERR!   peerOptional mongodb@"^3.6.0" from typeorm@0.3.11
npm ERR!   node_modules/typeorm
npm ERR!     typeorm@"^0.3.11" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Ante\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ante\AppData\Local\npm-cache\_logs\2023-02-06T07_51_32_579Z-debug-0.log
```

Can you help me about it?

**Comment by GoranTolusic** [comment]
try, npm i  - - force

**Comment by GoranTolusic** [comment]
add it immedietly to npm command after npm i

**Comment by anteljubic** [comment]
I can try with force, but this can't be a solution, there needs to be some way to fix the dependency issue

**Comment by GoranTolusic** [comment]
rm -rf node_modules/ && rm -rf package-lock.json && npm i --force &&
npm run seedAdmins && npm run seedNews && npm run start


copy/paste this into installAndRun into package.json, it should run.
It's probably due to the incompatibility between typeorm package and
mongoDb version. My local machine is on Windows and all worked
properly (except with building docker, i got the same error as you, so
i assume you are good with adding --force flag after npm i)

**Comment by GoranTolusic** [comment]
Hey, in attachments are corrected dependencies (at least I'm not giving
this error)

**Comment by anteljubic** [comment]
I can't see attachment, I'm writing you to the github issue, so it's not shown here

**Comment by GoranTolusic** [comment]
ok, i pushed to remote changes, you shoul pull it down and try again please

**Comment by anteljubic** [comment]
Thanks, it's working now
