### ISSUE TITLE
Fetch news

### ISSUE THREAD

**Issue by anteljubic** [GoranTolusic/news#2]
There is no route in postman collection or in routes folder to fetch all news.
I can see get post by id, but there are no posts in db, there is an external_news collection, does it mean it's populated wrong collection with posts?

**Comment by GoranTolusic** [comment]
I made filter posts route, which is kind of "get all" but much more sophisticated.
However, for creating post is necessary to have externalNewsId, and i forgot to add it for testing purposes, i will add it right now in few minutes)

**Comment by GoranTolusic** [comment]
I updated project with new get all route and added new docs, please check it out

**Comment by GoranTolusic** [comment]
Is everything working right now ?

**Comment by anteljubic** [comment]
I'm currently out of office next few days, something urgent came up, I'll
check when I'm back.. I'll ask coleague to take over in the meantime

uto, 7. velj 2023. 11:32 Goran Tolušić ***@***.***> je
napisao:

> Is everything working right now ?
>

**Comment by GoranTolusic** [comment]
ok, just make sure you pull again and check new postman collection

**Comment by anteljubic** [comment]
Now I can fetch all external news, but when I try Get Post method I'm always getting Not Found error response, like this post by id doesn't exist in db, I tried multiple id-s from external news.

**Comment by GoranTolusic** [comment]
did you create post? you need external new id for creating post, but these
are two different resources. external news are just bunch of fetched data
from newsapi, but essential for creating posts because i am maping some
data from external news into posts.

**Comment by anteljubic** [comment]
Okay, when I create post I can see it and get it by id, thanks
